In [85]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [86]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\archive (2)\swiggy.csv")
df.head()

,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [87]:
df.shape

(148541, 11)

In [88]:
df.columns

Index(['id', 'name', 'city', 'rating', 'rating_count', 'cost', 'cuisine',
       'lic_no', 'link', 'address', 'menu'],
      dtype='object')

In [89]:
# Removing unwanted columns 
df = df.drop(['rating_count','lic_no', 'link'], axis = 1 )
df.head()

,id,name,city,rating,cost,cuisine,address,menu
0,567335,AB FOODS POINT,Abohar,--,₹ 200,"Beverages,Pizzas","AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,₹ 200,"Sweets,Bakery","Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,₹ 100,Beverages,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,₹ 250,"Fast Food,Indian","Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,₹ 250,"Italian-American,Fast Food","GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [90]:
# Removing duplicate values 
df.drop_duplicates(inplace = True )
df.shape

(148541, 8)

In [91]:
df["rating"].unique()

array(['--', '4.4', '3.8', '3.7', '3.6', '4.0', '4.2', '4.7', '4.1',
       '3.5', '3.1', '3.4', '3.3', '4.8', '3.9', '2.7', '4.3', '2.9',
       '4.5', '2.5', '3.2', '2.4', '4.6', '3.0', '2.8', '2.3', '5.0',
       '2.6', '2.2', '1.4', '1.9', '4.9', '2.1', '1.3', '2.0', '1.8',
       '1.6', '1.1', '1.5', nan, '1.0', '1.2', '1.7'], dtype=object)

In [92]:
# Replace '--' with NaN
df['rating'] = df['rating'].replace('--', np.nan)

# Convert the column to numeric
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

In [93]:
df["rating"].fillna(df["rating"].mean(),inplace = True )

C:\Users\yadav\AppData\Local\Temp\ipykernel_19116\381516905.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["rating"].fillna(df["rating"].mean(),inplace = True )

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148541 entries, 0 to 148540
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   id       148541 non-null  int64
 1   name     148455 non-null  object
 2   city     148541 non-null  object
 3   rating   148541 non-null  float64
 4   cost     148410 non-null  object
 5   cuisine  148442 non-null  object
 6   address  148455 non-null  object
 7   menu     148541 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 9.1+ MB

In [95]:
df.dropna(inplace = True)
df.head()

,id,name,city,rating,cost,cuisine,address,menu
0,567335,AB FOODS POINT,Abohar,3.894461,₹ 200,"Beverages,Pizzas","AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.400000,₹ 200,"Sweets,Bakery","Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.800000,₹ 100,Beverages,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.700000,₹ 250,"Fast Food,Indian","Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,3.894461,₹ 250,"Italian-American,Fast Food","GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [96]:
df["city"].unique()

array(['Abohar', 'Adilabad', 'Adityapur', 'Adoni', 'Agartala', 'Agra',
       'Vastrapur,Ahmedabad', 'GOTA,Ahmedabad',
       'Paldi & Ambawadi,Ahmedabad', 'Ghatlodia,Ahmedabad',
       'Bopal,Ahmedabad', 'Gandhinagar,Ahmedabad', 'LalDarwaja,Ahmedabad',
       'Naranpura,Ahmedabad', 'Navrangpura,Ahmedabad',
       'Science City,Ahmedabad', 'Maninagar,Ahmedabad',
       'Chandkheda,Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer', 'Akola',
       'Alappuzha', 'Aligarh', 'Alipurduar', 'Allahabad', 'Alwar',
       'Ambala', 'Ambikapur', 'Ambur', 'Amravati', 'Amreli', 'Amritsar',
       'Anand', 'Anantapur', 'Ankleshwar', 'Arakkonam', 'Arambagh',
       'Arrah', 'Aruppukottai', 'Asansol', 'Aurangabad',
       'Aurangabad_bihar', 'Azamgarh', 'Baddi', 'Bagalkot', 'Bagdogra',
       'Bahadurgarh', 'Bahraich', 'Balaghat', 'Balangir', 'Balasore',
       'Ballari', 'Balrampur', 'Balurghat', 'Banda',
       'Yeshwanthpur,Bangalore', 'Geddalahalli,Bangalore',
       'Koramangala,Bangalore', 'JP Nagar,Bangalore',
       'Mahadevpura,Bangalore', 'HSR,Bangalore', 'Arekere,Bangalore',
       'Indiranagar,Bangalore', 'Banashankari,Bangalore',
       'Whitefield,Bangalore', 'Nagavara & Hennur,Bangalore',
       'Kammanahalli/Kalyan Nagar,Bangalore',
       'Kumaraswamy Layout & Uttarahalli,Bangalore', 'BTM,Bangalore',
       'Battarahalli,Bangalore', 'Basaveshwaranagar,Bangalore',
       'Frazer Town,Bangalore', 'Sanjay Nagar, New BEL Road,Bangalore',
       'Yelahanka,Bangalore', 'Majestic,Bangalore',
       'Kanakapura Road,Bangalore', 'R.T. Nagar,Bangalore',
       'Kadugodi,Bangalore', 'Marathahalli,Bangalore',
       'Rajarajeshwari Nagar,Bangalore', 'CV Raman Nagar,Bangalore',
       'Electronic City,Bangalore', 'Rajajinagar,Bangalore',
       'Kadubeesanahalli,Bangalore', 'Shantinagar,Bangalore',
       'Jayanagar,Bangalore', 'Central Bangalore,Bangalore', 'Bantwal',
       'Bapatlachirala', 'Baramati', 'Baran', 'Bardhaman', 'Bardoli',
       'Bareilly', 'Barmer', 'Barnala', 'Barshi', 'Barwani', 'Basirhat',
       'Basti', 'Batala', 'Bathinda', 'Beawar', 'Beed', 'Begusarai',
       'Bela-pratapgarh', 'Belgaum', 'Berhampore', 'Berhampur', 'Bettiah',
       'Betul', 'Bhadohi', 'Bhadrachalam', 'Bhagalpur', 'Bhandara',
       'Bharabanki', 'Bharatpur', 'Bharuch', 'Bhatkal', 'Bhavnagar',
       'Bhawanipatna', 'Bhilai', 'Bhilwara', 'Bhimavaram', 'Bhind',
       'Bhiwadi', 'Bhiwani', 'Bhopal', 'Bhubaneswar', 'Bhuj', 'Bhusawal',
       'Bidar', 'Biharsharif', 'Bijapur', 'Bijnor', 'Bikaner', 'Bilaspur',
       'Bilimora', 'Bodhan-rural', 'Bodinayakanur', 'Boisar', 'Bokaro',
       'Bolpur', 'Bongaigaon', 'Bongaon', 'Budaun', 'Budhwal',
       'Bulandshahr', 'Buldana', 'Bundi', 'Burhanpur', 'Buxar',
       'Central-goa', 'Chakdaha', 'Chalakkudy', 'Chalisgaon', 'Chandausi',
       'Greater Mohali,Chandigarh', 'Zirakpur,Chandigarh',
       'East Chd,Chandigarh', 'North Mohali,Chandigarh',
       'South Mohali,Chandigarh', 'West Chd,Chandigarh',
       'Panchkula,Chandigarh', 'South Chd,Chandigarh', 'Chandrapur',
       'Changanassery', 'Chengannur', 'Poonamallee,Chennai',
       'OMR Navalur,Chennai', 'Mylapore,Chennai', 'Guindy,Chennai',
       'Annanagar,Chennai', 'Chrompet,Chennai', 'Urapakkam,Chennai',
       'George Town,Chennai', 'KK Nagar,Chennai', 'OMR Perungudi,Chennai',
       'Kilpauk,Chennai', 'Vadapalani,Chennai', 'Perambur,Chennai',
       'Royapettah,Chennai', 'Tambaram,Chennai', 'Padur,Chennai',
       'Velachery,Chennai', 'Nungambakkam,Chennai', 'Avadi,Chennai',
       'Porur,Chennai', 'Ramapuram,Chennai', 'Perumbakkam,Chennai',
       'ECR-Kottivakkam,Chennai', 'Egmore,Chennai', 'Arumbakkam,Chennai',
       'Madipakkam,Chennai', 'Ambattur,Chennai',
       'Mahindra World City,Chennai', 'Alwarpet,Chennai',
       'Mogappair,Chennai', 'Iyyapanthangal,Chennai',
       'Medavakkam,Chennai', 'Villivakkam,Chennai', 'Karappakam,Chennai',
       'Royapuram,Chennai', 'Adyar,Chennai', 'T Nagar,Chennai',
       'Purasawalkam,Chennai', 'Cherthala', 'Chhapra', 'Chhatarpur',
       'Chhindwara', 'Chidambaram', 'Chikhli', 'Chikkaballapur',
       'Chikmagalur', 'Chiplun', 'Chitradurga', 'Chittoor', 'Chittorgarh',
       'Chopda', 'Churu', 'Peelamedu,Coimbatore', 'Hopes,Coimbatore',
       'Race Course,Coimbatore', 'Sai Baba Colony,Coimbatore',
       'Gandhipuram,Coimbatore', 'Saravanampatti,Coimbatore',
       'Ramanathapuram,Coimbatore', 'Coi_Ganapathy,Coimbatore',
       'Cooch-behar', 'Cuddalore', 'Cuttack', 'Dahanu', 'Dahod', 'Daman',
       'Darbhanga', 'Darjeeling', 'Dausa', 'Davanagere',
       'Chukkuwala,Dehradun', 'Hathibarkala,Dehradun',
       'Race Course Dehradun,Dehradun', 'Jakhan,Dehradun', 'Dehri',
       'GTB Nagar,Delhi', 'Jasola,Delhi', 'Greater Noida,Delhi',
       'Mayur Vihar,Delhi', 'BBK_MayurVihar,Delhi', 'Laxmi Nagar,Delhi',
       'Punjabi Bagh,Delhi', 'Old Delhi,Delhi', 'Khan Market,Delhi',
       'Greater Kailash 2,Delhi', 'Ashok Vihar,Delhi',
       'Noida Expressway,Delhi', 'South Extension,Delhi',
       'Greater Kailash New,Delhi', 'Vasant Kunj,Delhi',
       'Uttam Nagar,Delhi', 'Dilshad Gardens,Delhi',
       'Connaught Place,Delhi', 'South Campus,Delhi', 'Rohini,Delhi',
       'BBK_Chattarpur,Delhi', 'Chattarpur,Delhi', 'Lajpat Nagar,Delhi',
       'Kirti Nagar,Delhi', 'Indirapuram,Delhi', 'Dwarka,Delhi',
       'Rajouri Garden,Delhi', 'NSP,Delhi', 'Malviya Nagar,Delhi',
       'Sector 18,Delhi', 'Deoghar', 'Dewas', 'Dhanbad', 'Dhar',
       'Dharamshala', 'Dharmapuri', 'Dharwad', 'Dhoraji', 'Dhule',
       'Dibrugarh', 'Dimapur', 'Dindigul', 'Diu', 'Doddaballapura',
       'Duliajan', 'Dumka', 'Durgapur', 'Eluru', 'Erode', 'Etawah',
       'Faizabad', 'Faridabad', 'Faridkot', 'Farrukhabad', 'Fatehabad',
       'Fatehgarh-sahib', 'Fatehpur', 'Fazilka', 'Firozabad', 'Firozpur',
       'Gadag-betigeri', 'Gadwal', 'Gandhidham', 'Gangapur-city',
       'Gangtok', 'Gauriganj', 'Gaya', 'Giridih', 'Godhra', 'Gokak',
       'Golaghat', 'Gonda', 'Gondal', 'Gondia', 'Gopalganj', 'Gorakhpur',
       'Gudivada', 'Guna', 'Guntakal', 'Guntur', 'Gurdaspur',
       'Greenfields_FBD,Gurgaon', 'Sector-14,Gurgaon',
       'Sector 15_FBD,Gurgaon', 'New DLF Phase 4,Gurgaon',
       'NIT_FBD,Gurgaon', 'New Sohna Road,Gurgaon',
       'Old Gurgaon (Zone 6),Gurgaon', 'sohna road,Gurgaon',
       'New Cyber City,Gurgaon', 'Paltan Bazaar,Guwahati',
       'Ganeshguri,Guwahati', 'Gwalior', 'Habra', 'Haldia', 'Haldwani',
       'Halol', 'Hampi', 'Hansi', 'Hanumangarh', 'Hapur', 'Hardoi',
       'Haridwar', 'Hassan', 'Himmatnagar', 'Hindaun', 'Hinganghat',
       'Hisar', 'Hoshangabad', 'Hoshiarpur', 'Hospet', 'Hubli',
       'Kompally,Hyderabad', 'Himayath Nagar,Hyderabad',
       'Jubilee Hills,Hyderabad', 'Kachiguda,Hyderabad',
       'Begumpet,Hyderabad', 'Kothapet & Dilsukhnagar,Hyderabad',
       'Lingampally & Nalagandla,Hyderabad', 'Balanagar & Idpl,Hyderabad',
       'Kondapur,Hyderabad', 'Ameerpet,Hyderabad',
       'Abids & Koti,Hyderabad', 'Banjara Hills,Hyderabad',
       'Gachibowli,Hyderabad', 'Suncity & Bandlaguda,Hyderabad',
       'Vanasthalipuram,Hyderabad', 'Nampally,Hyderabad',
       'Miyapur,Hyderabad', 'Manikonda,Hyderabad', 'Madhapur,Hyderabad',
       'Mehdipatnam,Hyderabad', 'Kharkhana & Trimulgherry,Hyderabad',
       'West Marredpally,Hyderabad',
       'Tarnaka, Nacharam & Malkajigiri,Hyderabad',
       'Santoshnagar & Saidabad,Hyderabad', 'Alwal,Hyderabad',
       'Padmarao Nagar,Hyderabad', 'Kukatpally,Hyderabad',
       'Nizampet & Pragathi Nagar,Hyderabad', 'Tolichowki,Hyderabad',
       'Nanakramguda,Hyderabad', 'Attapur,Hyderabad', 'Ichalkaranji',
       'Imphal', 'Sarafa,Indore', 'Vijay Nagar,Indore',
       'South Tukoganj,Indore', 'Bhawar Kuan,Indore',
       'Old Palasia,Indore', 'New Palasia,Indore', 'Irinjalakuda',
       'Itanagar', 'Itarsi', 'Jabalpur', 'Jagdalpur', 'Jagraon',
       'Jagtial', 'Jahanabad', 'Manasarovar,Jaipur', 'Jalaun', 'Jalgaon',
       'Jalpaiguri', 'Jammu', 'Jamnagar', 'Jamshedpur', 'Jaunpur',
       'Jhalawar', 'Jhansi', 'Jhargram', 'Jhunjhunu', 'Jind', 'Jodhpur',
       'Jorhat', 'Junagadh', 'Kadapa', 'Kadayanallur', 'Kadiri',
       'Kaithal', 'Kakinada', 'Kalaburagi', 'Kalady', 'Kamareddy',
       'Kanchrapara', 'Kannauj', 'Kannur', 'Kanpur', 'Kanyakumari',
       'Kapurthala', 'Karad', 'Karaikkudi', 'Karimnagar', 'Karnal',
       'Karunagappaly', 'Karur', 'Karwar', 'Kasaragod', 'Kashipur',
       'Katihar', 'Katni', 'Kavali', 'Kayamkulam', 'Kendujhar',
       'Khamgaon', 'Khammam', 'Khandwa', 'Khanna', 'Kharagpur',
       'Kishanganj', 'Kishangarh', 'Vyttila,Kochi', 'Kalamassery,Kochi',
       'Aluva,Kochi', 'Panampilly Nagar,Kochi', 'Lulu Mall,Kochi',
       'Fort Kochi,Kochi', 'Thrippunithura,Kochi', 'Kodaikanal', 'Kohima',
       'Kolar', 'Kolhapur', 'Howrah,Kolkata', 'South Kolkata,Kolkata',
       'Rajarhat,Kolkata', 'Burrabazar,Kolkata', 'North Dumdum,Kolkata',
       'Chinar Park,Kolkata', 'Kestopur,Kolkata', 'Kidderpore,Kolkata',
       'Salt Lake,Kolkata', 'Ruby Area,Kolkata', 'Santoshpur,Kolkata',
       'Bally,Kolkata', 'Central Kolkata,Kolkata', 'Garia,Kolkata',
       'Tangra,Kolkata', 'Esplanade,Kolkata', 'Kankurgachi,Kolkata',
       'Naktala,Kolkata', 'Behala,Kolkata', 'Alipore,Kolkata',
       'Lake Town,Kolkata', 'Dumdum,Kolkata', 'Jadavpur,Kolkata',
       'Thakurpukur,Kolkata', 'Hatibagan,Kolkata', 'Kollam', 'Kopargaon',
       'Koppal', 'Korba', 'Kota', 'Kotdwar', 'Kothagudem',
       'Kothamanagalam', 'Kottakkal', 'Kottarakkara', 'Kottayam',
       'Kovilpatti', 'Kozhikode', 'Krishnagiri', 'Krishnanagar',
       'Kumarakom', 'Kumbakonam', 'Kumta', 'Kundapura', 'Kunnamkullam',
       'Kurnool', 'Kurukshetra', 'Lakhimpur', 'Lalitpur', 'Latur',
       'Lonavala', 'Lonavla', 'Gomti Nagar,Lucknow', 'Hazratganj,Lucknow',
       'Bbd,Lucknow', 'Ashiyana,Lucknow', 'Aminabad,Lucknow',
       'Aliganj,Lucknow', 'Alambagh,Lucknow', 'Indira Nagar,Lucknow',
       'Civil Lines,Ludhiana', 'BRS Nagar,Ludhiana',
       'Model Town,Ludhiana', 'Dugri,Ludhiana', 'Machilipatnam',
       'Madanapalle', 'Madhubani', 'Madikeri', 'Madurai', 'Mahbubnagar',
       'Malappuram', 'Malda', 'Malegaon', 'Malout', 'Manali',
       'Mancherial', 'Mandi-dabwali', 'Mandi-gobindgarh', 'Mandsaur',
       'Mandya', 'Mangaluru', 'Manipal', 'Manjeri', 'Mansa', 'Markapur',
       'Mathura', 'Maunath-bhanjan', 'Mayiladuthurai', 'Medinipur',
       'Meerut', 'Mehsana', 'Miryalaguda', 'Mirzapur', 'Modinagar',
       'Moga', 'Moodbidri', 'Moradabad', 'Morbi', 'Morena', 'Motihari',
       'Mount-abu', 'Mughalsarai', 'Muktsar', 'Virar,Mumbai',
       'Powai,Mumbai', 'Kamothe,Mumbai', 'Mulund,Mumbai',
       'Mahalaxmi Malabar Hill,Mumbai', 'Vashi,Mumbai',
       'Bandra West,Mumbai', 'Scruz Bandra East,Mumbai',
       'Fort Colaba,Mumbai', 'Bhayandar,Mumbai', 'Mahim Dadar,Mumbai',
       'Starbucks_BKC,Mumbai', 'Vasai,Mumbai', 'Matunga Wadala,Mumbai',
       'Airoli,Mumbai', 'Munger', 'Murshidabad', 'Mussoorie',
       'Muvattupuzha', 'Muzaffarnagar', 'Muzaffarpur',
       'Mysore North,Mysore', 'Mysore South,Mysore', 'Nabadwip', 'Nadiad',
       'Nagaon', 'Nagapattinam', 'Nagda', 'Nagercoil',
       'Dharampeth,Nagpur', 'Nandanvan,Nagpur', 'Sitabuldi,Nagpur',
       'Gandhibagh,Nagpur', 'Bajaj Nagar,Nagpur', 'Manish Nagar,Nagpur',
       'Sadar,Nagpur', 'Wardha Road,Nagpur', 'Naharlagun', 'Nainital',
       'Nalgonda', 'Namakkal', 'Nanded', 'Nandurbar', 'Nandyal', 'Nangal',
       'Naraingarh', 'Narasaraopet', 'Narnaul', 'Narsinghpur', 'Navsari',
       'Neemuch', 'Nellore', 'Neyveli', 'Nipani', 'Nirmal', 'Nizamabad',
       'Raj Nagar,Noida', 'Noida-1', 'North-goa', 'Ongole', 'Ooty',
       'Orai', 'Osmanabad', 'Pala', 'Palakkad', 'Palampur', 'Palani',
       'Palanpur', 'Pali', 'Panipat', 'Parbhani', 'Pathankot', 'Patiala',
       'Patna', 'Perinthalmanna', 'Phagwara', 'Pilibhit', 'Pondicherry',
       'Porbandar', 'Proddatur', 'Pudukkottai', 'Wanowrie,Pune',
       'Koregaon Park,Pune', 'Hadapsar,Pune', 'Warje,Pune',
       'Pimple Saudagar,Pune', 'Kothrud,Pune', 'Vishrantwadi,Pune',
       'Sangvi,Pune', 'Bibwewadi,Pune', 'Wakad,Pune', 'Kondhwa,Pune',
       'Swargate,Pune', 'Nigdi,Pune', 'Bavdhan,Pune', 'Bhosari,Pune',
       'Sinhgad Road,Pune', 'Wagholi,Pune', 'Narhe,Pune',
       'Hinjewadi,Pune', 'Bopodi,Pune', 'PCMC,Pune', 'Dhankawadi,Pune',
       'Viman Nagar,Pune', 'Aundh,Pune', 'Kalyani Nagar,Pune',
       'Kharadi,Pune', 'Shivaji Nagar,Pune', 'Hinjewadi Phase-3,Pune',
       'Baner,Pune', 'Magarpatta,Pune', 'Puri', 'Purnea', 'Purulia',
       'Pusad', 'Puttur', 'Rae-bareli', 'Raghunathpur', 'Raichur',
       'Raiganj', 'Raigarh', 'Raipur', 'Rajahmundry', 'Rajapalayam',
       'Rajkot', 'Rajnandgaon', 'Rajsamand', 'Ramagundam', 'Ramanagara',
       'Ramanathapuram', 'Rampur', 'Ranaghat-wb', 'Ranchi', 'Rangpo',
       'Ranibennur', 'Raniganj', 'Ratlam', 'Ratnagiri', 'Rayachoty',
       'Rewa', 'Rewari', 'Rishikesh', 'Rohtak', 'Roorkee', 'Ropar',
       'Rourkela', 'Rudrapur', 'Sagar', 'Saharanpur', 'Saharsa', 'Salem',
       'Samastipur', 'Sambalpur', 'Sangamner', 'Sangli', 'Sangrur',
       'Sasaram', 'Satara', 'Satna', 'Sawai-madhopur', 'Sehore',
       'Shahjahanpur', 'Shikohabad', 'Shillong', 'Shimla', 'Shivamogga',
       'Shivpuri', 'Shrirampur', 'Siddipet', 'Sikar', 'Silchar',
       'Siliguri', 'Silvassa', 'Sindhanur', 'Singrauli', 'Sirsa', 'Sirsi',
       'Sitapur', 'Sivakasi', 'Sivasagar', 'Siwan', 'Solan', 'Solapur',
       'Sonipat', 'South-goa', 'Sri-ganganagar', 'Srikakulam',
       'Srivilliputhur', 'Sultanpur', 'Athwa,Surat', 'Adajan,Surat',
       'Piplod,Surat', 'Suratgarh', 'Surendranagar-dudhrej', 'Suryapet',
       'Tadepalligudem', 'Tadpatri', 'Tanuku', 'Tarn-taran-sahib',
       'Tenkasi', 'Tezpur', 'Thalassery', 'Thanjavur', 'Theni',
       'Thiruvalla', 'Thiruvallur', 'Thiruvananthapuram', 'Thiruvarur',
       'Thodupuzha', 'Thoothukudi', 'Thrissur', 'Tinsukia', 'Tiptur',
       'Tirunelveli', 'Tirupati', 'Tirupur', 'Tiruvannamalai', 'Tohana',
       'Trichy', 'Tumakuru', 'Tuni', 'Udaipur', 'Udgir', 'Ujjain',
       'Uluberia', 'Uran-islampur', 'Akota,Vadodara', 'Alkapuri,Vadodara',
       'Vadiwadi,Vadodara', 'Valsad', 'Vapi', 'Varanasi', 'Varkala',
       'Vellore', 'Veraval', 'Vidisha',
       'Benz Circle and Auto Nagar,Vijayawada', 'Governorpet,Vijayawada',
       'Virudhunagar', 'Visnagar', 'N A D,Vizag', 'Gajuwaka,Vizag',
       'Jagadamba Junction,Vizag', 'MVP Colony,Vizag',
       'Dwarka Nagar,Vizag', 'Vizianagaram', 'Vyara', 'Waidhan',
       'Warangal', 'Wardha', 'Washim', 'Yamuna-nagar', 'Yavatmal'],
      dtype=object)

In [97]:
df.head()

,id,name,city,rating,cost,cuisine,address,menu
0,567335,AB FOODS POINT,Abohar,3.894461,₹ 200,"Beverages,Pizzas","AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.400000,₹ 200,"Sweets,Bakery","Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.800000,₹ 100,Beverages,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.700000,₹ 250,"Fast Food,Indian","Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,3.894461,₹ 250,"Italian-American,Fast Food","GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [98]:
df["cost"].unique()

array(['₹ 200', '₹ 100', '₹ 250', '₹ 150', '₹ 300', '₹ 700', '₹ 650',
       '₹ 400', '₹ 350', '₹ 60', '₹ 110', '₹ 399', '₹ 249', '₹ 500',
       '₹ 99', '₹ 120', '₹ 499', '₹ 299', '₹ 199', '₹ 50', '₹ 180',
       '₹ 349', '₹ 1000', '₹ 599', '₹ 600', '₹ 800', '₹ 450', '₹ 149',
       '₹ 290', '₹ 175', '₹ 125', '₹ 8', '₹ 375', '₹ 275', '₹ 425',
       '₹ 225', '₹ 325', '₹ 75', '₹ 160', '₹ 550', '₹ 220', '₹ 20',
       '₹ 59', '₹ 1200', '₹ 210', '₹ 30', '₹ 310', '₹ 70', '₹ 170',
       '₹ 449', '₹ 280', '₹ 320', '₹ 1300', '₹ 850', '₹ 900', '₹ 40',
       '₹ 1500', '₹ 140', '₹ 1100', '₹ 410', '₹ 80', '₹ 10', '₹ 1245',
       '₹ 510', '₹ 90', '₹ 260', '₹ 1800', '₹ 5', '₹ 240', '₹ 460',
       '₹ 1900', '₹ 352', '₹ 298', '₹ 2', '₹ 252', '₹ 330', '₹ 750',
       '₹ 130', '₹ 2000', '₹ 198', '₹ 230', '₹ 999', '₹ 3999', '₹ 235',
       '₹ 1600', '₹ 55', '₹ 179', '₹ 129', '₹ 360', '₹ 85', '₹ 248',
       '₹ 270', '₹ 25', '₹ 159', '₹ 370', '₹ 1050', '₹ 49', '₹ 699',
       '₹ 340', '₹ 190', '₹ 710', '₹ 1250', '₹ 178', '₹ 148', '₹ 380',
       '₹ 257', '₹ 171', '₹ 193', '₹ 189', '₹ 197', '₹ 336', '₹ 251',
       '₹ 245', '₹ 219', '₹ 188', '₹ 137', '₹ 164', '₹ 126', '₹ 268',
       '₹ 421', '₹ 540', '₹ 239', '₹ 14', '₹ 259', '₹ 1400', '₹ 497',
       '₹ 176', '₹ 255', '₹ 990', '₹ 158', '₹ 438', '₹ 354', '₹ 483',
       '₹ 69', '₹ 398', '₹ 39', '₹ 560', '₹ 278', '₹ 3000', '₹ 749',
       '₹ 2400', '₹ 950', '₹ 480', '₹ 258', '₹ 45', '₹ 359', '₹ 119',
       '₹ 224', '₹ 385', '₹ 590', '₹ 703', '₹ 347', '₹ 363', '₹ 790',
       '₹ 798', '₹ 15', '₹ 89', '₹ 355', '₹ 105', '₹ 719', '₹ 1099',
       '₹ 289', '₹ 440', '₹ 420', '₹ 559', '₹ 215', '₹ 390', '₹ 1',
       '₹ 138', '₹ 760', '₹ 595', '₹ 218', '₹ 65', '₹ 532', '₹ 288',
       '₹ 292', '₹ 214', '₹ 267', '₹ 284', '₹ 283', '₹ 746', '₹ 269',
       '₹ 287', '₹ 254', '₹ 502', '₹ 2022', '₹ 2500', '₹ 899', '₹ 163',
       '₹ 182', '₹ 203', '₹ 296', '₹ 597', '₹ 327', '₹ 293', '₹ 169',
       '₹ 799', '₹ 295', '₹ 263', '₹ 238', '₹ 378', '₹ 8000', '₹ 28',
       '₹ 498', '₹ 490', '₹ 459', '₹ 3500', '₹ 209', '₹ 183', '₹ 12',
       '₹ 79', '₹ 409', '₹ 196', '₹ 680', '₹ 888', '₹ 520', '₹ 279',
       '₹ 147', '₹ 475', '₹ 348', '₹ 1700', '₹ 630', '₹ 152', '₹ 580',
       '₹ 155', '₹ 1038', '₹ 384', '₹ 201', '₹ 111', '₹ 4', '₹ 195',
       '₹ 313', '₹ 229', '₹ 265', '₹ 118', '₹ 357', '₹ 294', '₹ 328',
       '₹ 640', '₹ 297', '₹ 430', '₹ 849', '₹ 649', '₹ 135', '₹ 675',
       '₹ 115', '₹ 132', '₹ 151', '₹ 396', '₹ 95', '₹ 102', '₹ 38', '₹ 3',
       '₹ 124', '₹ 106', '₹ 104', '₹ 32', '₹ 379', '₹ 98', '₹ 526',
       '₹ 820', '₹ 620', '₹ 108', '₹ 2509', '₹ 285', '₹ 6000', '₹ 5023',
       '₹ 204', '₹ 840', '₹ 839', '₹ 109', '₹ 308', '₹ 1650', '₹ 305',
       '₹ 84', '₹ 574', '₹ 748', '₹ 318', '₹ 2100', '₹ 1290', '₹ 57',
       '₹ 145', '₹ 185', '₹ 35', '₹ 458', '₹ 549', '₹ 660', '₹ 1045',
       '₹ 24', '₹ 880', '₹ 1999', '₹ 300350', '₹ 338', '₹ 493', '₹ 2200',
       '₹ 495', '₹ 444', '₹ 48', '₹ 780', '₹ 389', '₹ 3200', '₹ 416',
       '₹ 3360', '₹ 530', '₹ 366', '₹ 96', '₹ 221', '₹ 564', '₹ 920',
       '₹ 11', '₹ 395', '₹ 478', '₹ 208', '₹ 222', '₹ 144', '₹ 236',
       '₹ 276', '₹ 333', '₹ 139', '₹ 29', '₹ 315', '₹ 3100', '₹ 2700',
       '₹ 271', '₹ 351', '₹ 311', '₹ 286', '₹ 301', '₹ 256', '₹ 507',
       '₹ 87', '₹ 211', '₹ 22', '₹ 26', '₹ 5000', '₹ 2800', '₹ 598',
       '₹ 1001', '₹ 13', '₹ 156', '₹ 53', '₹ 165', '₹ 131', '₹ 666',
       '₹ 1150', '₹ 1020', '₹ 277', '₹ 1199', '₹ 177', '₹ 518', '₹ 54',
       '₹ 121', '₹ 670', '₹ 345', '₹ 94', '₹ 501', '₹ 216', '₹ 625',
       '₹ 88', '₹ 101', '₹ 312', '₹ 448', '₹ 64'], dtype=object)

In [99]:
df["cost"].unique()

array(['₹ 200', '₹ 100', '₹ 250', '₹ 150', '₹ 300', '₹ 700', '₹ 650',
       '₹ 400', '₹ 350', '₹ 60', '₹ 110', '₹ 399', '₹ 249', '₹ 500',
       '₹ 99', '₹ 120', '₹ 499', '₹ 299', '₹ 199', '₹ 50', '₹ 180',
       '₹ 349', '₹ 1000', '₹ 599', '₹ 600', '₹ 800', '₹ 450', '₹ 149',
       '₹ 290', '₹ 175', '₹ 125', '₹ 8', '₹ 375', '₹ 275', '₹ 425',
       '₹ 225', '₹ 325', '₹ 75', '₹ 160', '₹ 550', '₹ 220', '₹ 20',
       '₹ 59', '₹ 1200', '₹ 210', '₹ 30', '₹ 310', '₹ 70', '₹ 170',
       '₹ 449', '₹ 280', '₹ 320', '₹ 1300', '₹ 850', '₹ 900', '₹ 40',
       '₹ 1500', '₹ 140', '₹ 1100', '₹ 410', '₹ 80', '₹ 10', '₹ 1245',
       '₹ 510', '₹ 90', '₹ 260', '₹ 1800', '₹ 5', '₹ 240', '₹ 460',
       '₹ 1900', '₹ 352', '₹ 298', '₹ 2', '₹ 252', '₹ 330', '₹ 750',
       '₹ 130', '₹ 2000', '₹ 198', '₹ 230', '₹ 999', '₹ 3999', '₹ 235',
       '₹ 1600', '₹ 55', '₹ 179', '₹ 129', '₹ 360', '₹ 85', '₹ 248',
       '₹ 270', '₹ 25', '₹ 159', '₹ 370', '₹ 1050', '₹ 49', '₹ 699',
       '₹ 340', '₹ 190', '₹ 710', '₹ 1250', '₹ 178', '₹ 148', '₹ 380',
       '₹ 257', '₹ 171', '₹ 193', '₹ 189', '₹ 197', '₹ 336', '₹ 251',
       '₹ 245', '₹ 219', '₹ 188', '₹ 137', '₹ 164', '₹ 126', '₹ 268',
       '₹ 421', '₹ 540', '₹ 239', '₹ 14', '₹ 259', '₹ 1400', '₹ 497',
       '₹ 176', '₹ 255', '₹ 990', '₹ 158', '₹ 438', '₹ 354', '₹ 483',
       '₹ 69', '₹ 398', '₹ 39', '₹ 560', '₹ 278', '₹ 3000', '₹ 749',
       '₹ 2400', '₹ 950', '₹ 480', '₹ 258', '₹ 45', '₹ 359', '₹ 119',
       '₹ 224', '₹ 385', '₹ 590', '₹ 703', '₹ 347', '₹ 363', '₹ 790',
       '₹ 798', '₹ 15', '₹ 89', '₹ 355', '₹ 105', '₹ 719', '₹ 1099',
       '₹ 289', '₹ 440', '₹ 420', '₹ 559', '₹ 215', '₹ 390', '₹ 1',
       '₹ 138', '₹ 760', '₹ 595', '₹ 218', '₹ 65', '₹ 532', '₹ 288',
       '₹ 292', '₹ 214', '₹ 267', '₹ 284', '₹ 283', '₹ 746', '₹ 269',
       '₹ 287', '₹ 254', '₹ 502', '₹ 2022', '₹ 2500', '₹ 899', '₹ 163',
       '₹ 182', '₹ 203', '₹ 296', '₹ 597', '₹ 327', '₹ 293', '₹ 169',
       '₹ 799', '₹ 295', '₹ 263', '₹ 238', '₹ 378', '₹ 8000', '₹ 28',
       '₹ 498', '₹ 490', '₹ 459', '₹ 3500', '₹ 209', '₹ 183', '₹ 12',
       '₹ 79', '₹ 409', '₹ 196', '₹ 680', '₹ 888', '₹ 520', '₹ 279',
       '₹ 147', '₹ 475', '₹ 348', '₹ 1700', '₹ 630', '₹ 152', '₹ 580',
       '₹ 155', '₹ 1038', '₹ 384', '₹ 201', '₹ 111', '₹ 4', '₹ 195',
       '₹ 313', '₹ 229', '₹ 265', '₹ 118', '₹ 357', '₹ 294', '₹ 328',
       '₹ 640', '₹ 297', '₹ 430', '₹ 849', '₹ 649', '₹ 135', '₹ 675',
       '₹ 115', '₹ 132', '₹ 151', '₹ 396', '₹ 95', '₹ 102', '₹ 38', '₹ 3',
       '₹ 124', '₹ 106', '₹ 104', '₹ 32', '₹ 379', '₹ 98', '₹ 526',
       '₹ 820', '₹ 620', '₹ 108', '₹ 2509', '₹ 285', '₹ 6000', '₹ 5023',
       '₹ 204', '₹ 840', '₹ 839', '₹ 109', '₹ 308', '₹ 1650', '₹ 305',
       '₹ 84', '₹ 574', '₹ 748', '₹ 318', '₹ 2100', '₹ 1290', '₹ 57',
       '₹ 145', '₹ 185', '₹ 35', '₹ 458', '₹ 549', '₹ 660', '₹ 1045',
       '₹ 24', '₹ 880', '₹ 1999', '₹ 300350', '₹ 338', '₹ 493', '₹ 2200',
       '₹ 495', '₹ 444', '₹ 48', '₹ 780', '₹ 389', '₹ 3200', '₹ 416',
       '₹ 3360', '₹ 530', '₹ 366', '₹ 96', '₹ 221', '₹ 564', '₹ 920',
       '₹ 11', '₹ 395', '₹ 478', '₹ 208', '₹ 222', '₹ 144', '₹ 236',
       '₹ 276', '₹ 333', '₹ 139', '₹ 29', '₹ 315', '₹ 3100', '₹ 2700',
       '₹ 271', '₹ 351', '₹ 311', '₹ 286', '₹ 301', '₹ 256', '₹ 507',
       '₹ 87', '₹ 211', '₹ 22', '₹ 26', '₹ 5000', '₹ 2800', '₹ 598',
       '₹ 1001', '₹ 13', '₹ 156', '₹ 53', '₹ 165', '₹ 131', '₹ 666',
       '₹ 1150', '₹ 1020', '₹ 277', '₹ 1199', '₹ 177', '₹ 518', '₹ 54',
       '₹ 121', '₹ 670', '₹ 345', '₹ 94', '₹ 501', '₹ 216', '₹ 625',
       '₹ 88', '₹ 101', '₹ 312', '₹ 448', '₹ 64'], dtype=object)

In [100]:
df.head()

,id,name,city,rating,cost,cuisine,address,menu
0,567335,AB FOODS POINT,Abohar,3.894461,₹ 200,"Beverages,Pizzas","AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.400000,₹ 200,"Sweets,Bakery","Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.800000,₹ 100,Beverages,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.700000,₹ 250,"Fast Food,Indian","Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,3.894461,₹ 250,"Italian-American,Fast Food","GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [101]:
df['cost'] = (
    df['cost']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
    .astype(float)
)

In [102]:
df['cost'].head()

0    200.0
1    200.0
2    100.0
3    250.0
4    250.0
Name: cost, dtype: float64

In [103]:
#Cleaning cuisine
cuisine = df["cuisine"].value_counts(ascending = False)
cuisine

cuisine
North Indian,Chinese         6469
Indian                       6406
Chinese                      5049
North Indian                 4775
Indian,Chinese               4370
                             ...
Vietnamese,Pan-Asian            1
Healthy Food,Pan-Asian          1
Home Food,Naga                  1
Korean,Desserts                 1
Barbecue,Italian-American       1
Name: count, Length: 2132, dtype: int64

In [104]:
cuisine_lessthan1000 = cuisine[cuisine<1000]
cuisine_lessthan1000

cuisine
Pizzas,Fast Food             964
Indian,North Indian          949
Indian,Snacks                849
Indian,Biryani               835
Snacks,Beverages             810
                            ...
Vietnamese,Pan-Asian           1
Healthy Food,Pan-Asian         1
Home Food,Naga                 1
Korean,Desserts                1
Barbecue,Italian-American      1
Name: count, Length: 2098, dtype: int64

In [105]:
def handle_cuisine(value):
    if (value in cuisine_lessthan1000):
        return "other"
    else:
        return value
df["cuisine"] = df["cuisine"].apply(handle_cuisine)
df["cuisine"].value_counts()

cuisine
other                        72788
North Indian,Chinese          6469
Indian                        6406
Chinese                       5049
North Indian                  4775
Indian,Chinese                4370
South Indian                  3302
Bakery                        3131
Chinese,Indian                2308
Chinese,North Indian          2286
Bakery,Desserts               2233
Biryani                       2227
Pizzas                        2215
Beverages                     2157
North Indian,Indian           2004
Snacks                        1785
Fast Food                     1671
Biryani,North Indian          1643
Chinese,Snacks                1622
Fast Food,Snacks              1601
Ice Cream,Desserts            1577
Biryani,Chinese               1485
North Indian,Biryani          1458
Desserts                      1335
North Indian,South Indian     1307
Chinese,Fast Food             1275
North Indian,Snacks           1240
Biryani,Indian                1204
South Indian,North Indian     1201
South Indian,Chinese          1135
North Indian,Punjabi          1071
Beverages,Snacks              1019
Pizzas,Italian                1018
Ice Cream                     1016
Desserts,Ice Cream            1015
Name: count, dtype: int64

In [106]:
df.head()

,id,name,city,rating,cost,cuisine,address,menu
0,567335,AB FOODS POINT,Abohar,3.894461,200.0,other,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.400000,200.0,other,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.800000,100.0,Beverages,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.700000,250.0,other,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,3.894461,250.0,other,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [107]:
address = df["address"].value_counts(ascending = False)
address_lessthan300 = address[address<300]

def handle_address(value):
    if(value in address_lessthan300):
        return "others"
    else:
        return value

df["address"] = df["address"].apply(handle_address)
df["address"].value_counts()

address
others    148398
Name: count, dtype: int64

In [108]:
cuisine = df["cuisine"].value_counts(ascending = False)

cuisine_lessthan100 = cuisine[cuisine<100]

def handle_cuisine(value):
    if(value in cuisine_lessthan100):
        return "others"
    else:
        return value
df["cuisine"] = df["cuisine"].apply(handle_cuisine)
df["cuisine"].value_counts()

cuisine
other                        72788
North Indian,Chinese          6469
Indian                        6406
Chinese                       5049
North Indian                  4775
Indian,Chinese                4370
South Indian                  3302
Bakery                        3131
Chinese,Indian                2308
Chinese,North Indian          2286
Bakery,Desserts               2233
Biryani                       2227
Pizzas                        2215
Beverages                     2157
North Indian,Indian           2004
Snacks                        1785
Fast Food                     1671
Biryani,North Indian          1643
Chinese,Snacks                1622
Fast Food,Snacks              1601
Ice Cream,Desserts            1577
Biryani,Chinese               1485
North Indian,Biryani          1458
Desserts                      1335
North Indian,South Indian     1307
Chinese,Fast Food             1275
North Indian,Snacks           1240
Biryani,Indian                1204
South Indian,North Indian     1201
South Indian,Chinese          1135
North Indian,Punjabi          1071
Beverages,Snacks              1019
Pizzas,Italian                1018
Ice Cream                     1016
Desserts,Ice Cream            1015
Name: count, dtype: int64